name:  start workers
on:
  issues:
    types: labeled
  schedule:
    - cron: 0 */8 * * *
jobs:
 StartWorks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.list_dirs.outputs.matrix}}
    steps:  
    - uses: actions/checkout@v2
      with:
       ref: dev
       path: dev
    - id: list_dirs
      run: echo "::set-output name=matrix::$(ls $PWD/dev/files/*.c|jq -cnR '[inputs | select(length>0)]')"

 ManyWorks:
    runs-on: ubuntu-latest
    needs: StartWorks
    strategy:
      fail-fast: false
      matrix:
        job: ${{fromJson(needs.StartWorks.outputs.matrix)}}
    steps:
    - uses: actions/checkout@v2
      with:
       ref: dev
       path: dev
    - name: start $JOB
      run: |
          sudo python3 ./dev/code/myworker.py $JOB ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }}
      env:
        JOB: ${{ matrix.job }}
 EndWorks:
    runs-on: ubuntu-latest
#    if: always()
    needs: [ManyWorks] 
    steps:
    - uses: actions/checkout@v2
      with:
       ref: dev
       path: dev
    - name: rename file tasks
      run: |
        find . -type f -name './dev/files/*.c' -exec sh -c 'x="{}"; mv "$x" "${x}_"' \;
        ls -al ./dev/files/
    - name: push changes
        sudo git config --local user.email "${GITHUB_ACTOR}@gmail.com"
        sudo git config --local user.name "${GITHUB_ACTOR}"
        sudo git remote -v
        sudo git add files/*
        sudo git commit -m "rename result"
        sudo git push "https://gergimentr:${{ secrets.ACCESS_TOKEN }}@github.com/gergimentr/myKleeChecker.git" HEAD:dev --force 
